name: Gitrack Shield Action

on: [pull_request]

jobs:
  secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@master
    - name: Setup Gitrack Shield
      run: |
        curl -sfL https://storage.googleapis.com/security-tests-8a473ab3b5/gitrack-shield-scanner.sh | sh -

    - name: Running Gitrack Shield (Secrets Scanning)
      run: |
        python3 gitrack-shield/gitrack-shield.py ${{ github.workspace }}
